apiVersion: v1
kind: Secret
metadata:
  name: keke-secrets
  namespace: keke
  labels:
    app: keke-excel-tool
type: Opaque
data:
  # AI API Keys (base64 encoded)
  OPENAI_API_KEY: ""  # Add your base64 encoded OpenAI API key
  ANTHROPIC_API_KEY: ""  # Add your base64 encoded Anthropic API key
  
  # Database Credentials
  POSTGRES_PASSWORD: cGFzc3dvcmQ=  # "password" base64 encoded
  MONGODB_PASSWORD: cGFzc3dvcmQ=  # "password" base64 encoded
  
  # Security Keys
  JWT_SECRET: ""  # Add your base64 encoded JWT secret
  ENCRYPTION_KEY: ""  # Add your base64 encoded encryption key
  
  # Cloud Storage Credentials
  AWS_ACCESS_KEY_ID: ""  # Add your base64 encoded AWS access key
  AWS_SECRET_ACCESS_KEY: ""  # Add your base64 encoded AWS secret key
  AZURE_STORAGE_CONNECTION_STRING: ""  # Add your base64 encoded Azure connection string
  GOOGLE_APPLICATION_CREDENTIALS: ""  # Add your base64 encoded Google credentials
  
  # External Service Keys
  EXTERNAL_API_KEY: ""  # Add your base64 encoded external API key
  SLACK_WEBHOOK_URL: ""  # Add your base64 encoded Slack webhook URL
  
  # Email Configuration
  SMTP_PASSWORD: ""  # Add your base64 encoded SMTP password
